# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(max_length=100)),
                ('bug_description', models.TextField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(verbose_name='date completed')),
            ],
        ),
        migrations.CreateModel(
            name='Enhancement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enhancement_title', models.CharField(max_length=100)),
                ('enhancement_description', models.TextField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(verbose_name='date completed')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('date_started', models.DateTimeField(verbose_name='date started')),
            ],
        ),
        migrations.AddField(
            model_name='enhancement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
