# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.TextField(blank=True, max_length=500, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(verbose_name='date completed')),
                ('date_started', models.DateTimeField(verbose_name='date started')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_creator_set', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executor_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
