# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date completed'),
        ),
    ]
